server:
  port: 8888
shapefile:
  dir: D:/zgis/geotools/shapefiles/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.79.94:3306/geom
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: cx.shapefile